// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package pgstore

import (
	"context"
)

type Querier interface {
	CreateDefaultSetForExercise(ctx context.Context, arg CreateDefaultSetForExerciseParams) (EtrackerappSet, error)
	CreateSetForExercise(ctx context.Context, arg CreateSetForExerciseParams) (EtrackerappSet, error)
	CreateUserDefaultExercise(ctx context.Context) error
	CreateUserExercise(ctx context.Context, arg CreateUserExerciseParams) (interface{}, error)
	CreateUserImage(ctx context.Context, arg CreateUserImageParams) (EtrackerappImage, error)
	CreateUserWorkout(ctx context.Context, userID int64) (EtrackerappWorkout, error)
	CreateUsers(ctx context.Context, arg CreateUsersParams) (EtrackerappUser, error)
	DeleteUserExercise(ctx context.Context, arg DeleteUserExerciseParams) error
	DeleteUserImage(ctx context.Context, userID int64) error
	DeleteUserWorkouts(ctx context.Context, userID int64) error
	DeleteUsers(ctx context.Context, userID int64) error
	DeleteWorkoutByIDForUser(ctx context.Context, arg DeleteWorkoutByIDForUserParams) error
	GetUser(ctx context.Context, userID int64) (EtrackerappUser, error)
	GetUserByName(ctx context.Context, userName string) (EtrackerappUser, error)
	GetUserImage(ctx context.Context, userID int64) (GetUserImageRow, error)
	GetWorkoutsForUserID(ctx context.Context, userID int64) ([]GetWorkoutsForUserIDRow, error)
	ListImages(ctx context.Context) ([]EtrackerappImage, error)
	ListUserExercises(ctx context.Context, userID int64) ([]string, error)
	ListUsers(ctx context.Context) ([]EtrackerappUser, error)
	UpdateSet(ctx context.Context, arg UpdateSetParams) (EtrackerappSet, error)
	UpsertUserImage(ctx context.Context, imageData []byte) (int64, error)
}

var _ Querier = (*Queries)(nil)
