// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package pgstore

import (
	"context"
)

type Querier interface {
	// insert a new exercise
	CreateExercise(ctx context.Context, exerciseName string) (int64, error)
	// insert new exercise sets
	CreateSet(ctx context.Context, arg CreateSetParams) (GowebappSet, error)
	// insert a new image
	CreateUserImage(ctx context.Context, arg CreateUserImageParams) (GowebappImage, error)
	// insert new user
	CreateUsers(ctx context.Context, arg CreateUsersParams) (GowebappUser, error)
	// insert new workouts
	CreateWorkout(ctx context.Context, arg CreateWorkoutParams) (GowebappWorkout, error)
	// delete a particular exercise
	DeleteExercise(ctx context.Context, exerciseID int64) error
	// delete a particular exercise sets
	DeleteSets(ctx context.Context, setID int64) error
	// delete a particular user's image
	DeleteUserImage(ctx context.Context, userID int64) error
	// delete a particular user's workouts
	DeleteUserWorkouts(ctx context.Context, userID int64) error
	// delete a particular user
	DeleteUsers(ctx context.Context, userID int64) error
	// get users of a particular user_id
	GetUser(ctx context.Context, userID int64) (GowebappUser, error)
	// get a particular user image
	GetUserImage(ctx context.Context, userID int64) (GetUserImageRow, error)
	// get a particular user information, exercise sets and workouts
	GetUserSets(ctx context.Context, userID int64) ([]GetUserSetsRow, error)
	// get a particular user information and workouts
	GetUserWorkout(ctx context.Context, userID int64) ([]GetUserWorkoutRow, error)
	// get all exercises ordered by the exercise name
	ListExercises(ctx context.Context) ([]GowebappExercise, error)
	// get all images ordered by the id
	ListImages(ctx context.Context) ([]GowebappImage, error)
	// get all exercise sets ordered by weight
	ListSets(ctx context.Context) ([]GowebappSet, error)
	// get all users ordered by the username
	ListUsers(ctx context.Context) ([]GowebappUser, error)
	// get all workouts ordered by id
	ListWorkouts(ctx context.Context) ([]GowebappWorkout, error)
	// insert a sets id
	UpdateSet(ctx context.Context, arg UpdateSetParams) (GowebappSet, error)
	// insert or update exercise of a particular id
	UpsertExercise(ctx context.Context, exerciseName string) (int64, error)
	// insert or update image of a particular id
	UpsertUserImage(ctx context.Context, imageData []byte) (int64, error)
	// insert or update workouts based of a particular ID
	UpsertWorkout(ctx context.Context, arg UpsertWorkoutParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
